SVP/SVP/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('videos.urls')),
]

SVP/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("create", views.create),
    path("login", views.login, name="login"),
    path("delete", views.delete)
]

SVP/videos/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.main, name="main"),
    path("account_main/<id>", views.account_main, name="account_main"),
    path("view/<id>", views.view),
    path("account/<id>", views.account_video),
    path("account/add/<id>", views.add_video),
    path("account/change/<id>/<video_id>", views.change_video),
    path("account/delete/<id>/<video_id>", views.delete_video),
    path("find/<input_string>", views.find),
    path("channel/<id>", views.channel),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SVP/users/models.py
from django.db import models
from hashlib import sha256


# Create your models here.


def make_password(string):
    return sha256(str(string).encode()).hexdigest()


class Account(models.Model):
    username = models.CharField(max_length=15)
    password = models.CharField(max_length=200)

    def __str__(self):
        return self.username

SVP/videos/models.py
from django.db import models
from users.models import Account


# Create your models here.


class Video(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    title = models.CharField(max_length=25)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def cover_upload_to(self, filename):
        return f'Files/{self.account.id}/Covers/{filename}'

    def file_upload_to(self, filename):
        return f'Files/{self.account.id}/Videos/{filename}'

    cover = models.FileField(upload_to=cover_upload_to)
    file = models.FileField(upload_to=file_upload_to)

    def __str__(self):
        return self.title

SVP/users/views.py
from django.shortcuts import render, redirect
from .models import make_password, Account
# Create your views here.
# create account
# log in account
# delete account


def create(request):
    template_name = "users/create_page.html"
    if request.method == "POST":
        username = request.POST['username']
        if Account.objects.filter(username=username).exists():
            return render(request, template_name, {"error": "Username is already taken"})
        password = make_password(request.POST['password'])
        account = Account(username=username, password=password)
        account.save()
        user = Account.objects.filter(username=username)
        request.session[f"{account.id}"] = 'True'
        return redirect(f"/account_main/{user[0].id}")

    return render(request, template_name)


def login(request):
    template_name = "users/login_page.html"

    if request.method == "POST":
        username = request.POST['username']
        password = make_password(request.POST['password'])

        if Account.objects.filter(username=username).exists():
            user = Account.objects.filter(username=username)

            if user[0].password == password:
                request.session[f"{user[0].id}"] = 'True'

                return redirect(f"/account_main/{user[0].id}")
            return render(request, template_name, {"error": "Password is not valid"})
        return render(request, template_name, {"error": "Username is not valid"})
    return render(request, template_name)


def delete(request):
    template_name = "users/delete_page.html"

    if request.method == "POST":
        username = request.POST['username']
        password = make_password(request.POST['password'])

        if Account.objects.filter(username=username).exists():
            user = Account.objects.filter(username=username)

            if user[0].password == password:
                del request.session[f"{user[0].id}"]
                user.delete()
                return redirect("main")
            return render(request, template_name, {"error": "Password is not valid"})
        return render(request, template_name, {"error": "Username is not valid"})
    return render(request, template_name)

SVP/videos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Video
from users.models import Account
import difflib

# Create your views here.
# see videos


def account_main(request, id):
    template_name = "videos/account_main_page.html"
    if request.session.get(f'{id}', False):
        if request.method == "POST":

            return redirect(f"/find/{request.POST.get('data')}")

        videos = Video.objects.all()

        return render(request, template_name, {"videos": videos, "account": Account.objects.get(id=id)})

    return redirect("main")


def main(request):

    template_name = "videos/main.html"
    if request.method == "POST":
        return redirect(f"/find/{request.POST.get('data')}")
    videos = Video.objects.all()

    return render(request, template_name, {"videos": videos})


def view(request, id):
    template_name = "videos/view_page.html"
    try:
        video = Video.objects.filter(id=id)[0]

        return render(request, template_name, {"video": video})
    except IndexError:
        return render(request, template_name, {"error": "No such video"})


def account_video(request, id):
    template_name = "videos/account_video_page.html"
    if request.session.get(f'{id}', False):
        videos_of_channel = Video.objects.filter(account=Account.objects.get(id=id))

        return render(request, template_name, {"videos": videos_of_channel, "id": id, "name": Account.objects.get(id=id).username})

    return redirect("login")


def add_video(request, id):
    template_name = "videos/add_video_page.html"
    if request.session.get(f'{id}', False):
        if request.method == "POST":
            account = Account.objects.get(id=id)
            title = request.POST['title']
            cover = request.FILES.get('cover')
            file = request.FILES.get('file')
            if account and title and cover and file:
                video = Video(account=account, title=title, cover=cover, file=file)
                video.save()
                return redirect(f'/account/{id}')

        return render(request, template_name, {"id": id})

    return redirect("login")


def change_video(request, id, video_id):
    template_name = "videos/change_video_page.html"

    if request.session.get(f'{id}', False):
        account = get_object_or_404(Account, id=id)
        video = get_object_or_404(Video, id=video_id, account=account)

        if request.method == "POST":
            title = request.POST.get('title')
            cover = request.FILES.get('cover')
            file = request.FILES.get('file')


            if title:
                video.title = title
            if cover:
                video.cover = cover
            if file:
                video.file = file

            video.save()
            return redirect(f'/account/{id}')

        return render(request, template_name)

    return redirect("login")


def delete_video(request, id, video_id):
    template_name = "videos/delete_video_page.html"
    if request.session.get(f'{id}', False):
        if request.method == "POST":
            video = Video.objects.get(id=video_id)
            video.delete()
            return redirect(f'/account/{id}')

        return render(request, template_name)

    return redirect("login")


def find(request, input_string):
    template_name = "videos/find_page.html"
    videos = []
    for el in Video.objects.all():
        videos.append(el.title)

    closest_match = difflib.get_close_matches(input_string,  videos, n=3)

    if closest_match:
        return render(request, template_name, {"video": Video.objects.get(title=closest_match[0])})

    else:
        return render(request, template_name)


def channel(request, id):
    template_name = "videos/channel.html"
    account = Account.objects.get(id=id)

    videos = Video.objects.filter(account=account)

    return render(request, template_name, {"videos": videos, "account": account.username})

SVP/users/templates/users/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    <title>Video Platform</title>
</head>
<body>
    <div class="container">
        <h1>Video Platform</h1>
        {% block 'body' %}
        {% endblock %}
    </div>
</body>
</html>

SVP/users/templates/users/create_page.html
{% extends 'users/base.html' %}


{% block 'body' %}

<form method="post">
    {% csrf_token %}


    <div class="container">

            <div class="form-row field-username">


                    <div>

                            <div class="flex-container">

                                    <label class="required" for="id_username">Username:</label>

                                        <input type="text" name="username" class="vTextField" maxlength="15" required="" id="id_username">


                            </div>

                    </div>


            </div>

            <div class="form-row field-password">


                    <div>

                            <div class="flex-container">

                                    <label class="required" for="id_password">Password:</label>

                                        <input type="text" name="password" class="vTextField" maxlength="15" required="" id="id_password">


                            </div>

                    </div>


            </div>


    </div>
    <span></span>
    <div class="container">
        {% if error %}
            <span>{{error}}</span>
        {% endif %}
        <input type="submit" value="Save" class="animated-submit" name="_save" id="inp">
        <a href="/login" class="blue-link">Do you have an account ?</a>
    </div>
</form>







{% endblock %}

SVP/users/templates/users/delete_page.html
{% extends 'users/base.html' %}


{% block 'body' %}

<form method="post">
    {% csrf_token %}


    <div class="container">

            <div class="form-row field-username">


                    <div>

                            <div class="flex-container">

                                    <label class="required" for="id_username">Username:</label>

                                        <input type="text" name="username" class="vTextField" maxlength="15" required="" id="id_username">


                            </div>

                    </div>


            </div>

            <div class="form-row field-password">


                    <div>

                            <div class="flex-container">

                                    <label class="required" for="id_password">Password:</label>

                                        <input type="text" name="password" class="vTextField" maxlength="15" required="" id="id_password">


                            </div>

                    </div>


            </div>


    </div>
    <span></span>
    <div class="container">
        {% if error %}
            <span>{{error}}</span>
        {% endif %}

        <input type="submit" value="Delete" class="animated-submit" name="_save" id="inp">
    </div>
</form>







{% endblock %}

SVP/users/templates/users/login_page.html
{% extends 'users/base.html' %}


{% block 'body' %}

<form method="post">
    {% csrf_token %}


    <div class="container">

            <div class="form-row field-username">


                    <div>

                            <div class="flex-container">

                                    <label class="required" for="id_username">Username:</label>

                                        <input type="text" name="username" class="vTextField" maxlength="15" required="" id="id_username">


                            </div>

                    </div>


            </div>

            <div class="form-row field-password">


                    <div>

                            <div class="flex-container">

                                    <label class="required" for="id_password">Password:</label>

                                        <input type="text" name="password" class="vTextField" maxlength="15" required="" id="id_password">


                            </div>

                    </div>


            </div>


    </div>
    <span></span>
    <div class="container">
        {% if error %}
            <span>{{error}}</span>
        {% endif %}
        <input type="submit" value="Log In" class="animated-submit" name="_save" id="inp">
        <a href="/create" class="blue-link">Don't you have an account?</a>
    </div>
</form>







{% endblock %}

SVP/videos/templates/videos/account_main_page.html
{% extends 'videos/base.html' %}


{% block 'body' %}
    <div class="container"><a href="/account/{{account.id}}" class="blue-link">Account</a></div>
    <p></p>
     <form method="post">
         {% csrf_token %}
        <div class="container">
            <input type="search" placeholder="video platform" name="data" class="search_inp">
            <input type="submit" value="search">
        </div>
    </form>
    <p></p>
    <div>
        {% for video in videos %}
            <div class="video_container">
                <a href="/view/{{video.id}}" class="no-underline">
                <img src="{{ video.cover.url }}" width="300" height="200" alt="{{video.title}}">
                <h3>{{video.title}}</h3>
                <h6>{{video.uploaded_at}}</h6>
                </a>
            </div>
        {% endfor %}
    </div>

{% endblock %}

SVP/videos/templates/videos/account_video_page.html
{% extends 'videos/base.html' %}

{% block 'body' %}
    <h1>{{name}}</h1>
    <p></p>
    <a class="blue-link" href="/account_main/{{id}}">back</a>
    <a class="blue-link" href="add/{{id}}">Add</a>
    <p></p>
    {% for video in videos %}

        <div class="video_container">

            <img src="{{ video.cover.url }}" width="300" height="200" alt="{{video.title}}">
            <h3>{{video.title}}</h3>
            <h6>{{video.uploaded_at}}</h6>
            <a href="/view/{{video.id}}" class="blue-link">view</a>
            <a href="/account/change/{{id}}/{{video.id}}" class="blue-link">change</a>
            <a href="delete/{{id}}/{{video.id}}" class="blue-link">delete</a>
        </div>
    {% endfor %}


{% endblock %}

SVP/videos/templates/videos/add_video_page.html
{% extends 'videos/base.html' %}


{% block 'body' %}


<form enctype="multipart/form-data" method="post" id="video_form" novalidate="">
{% csrf_token %}



<fieldset class="module aligned ">

        <div class="form-row field-title">


                <div>

                        <div class="flex-container">

                                <label class="required" for="id_title">Title:</label>

                                    <input type="text" name="title" class="vTextField" maxlength="25" required="" id="id_title">


                        </div>

                </div>


        </div>

        <div class="form-row field-cover">


                <div>

                        <div class="flex-container">

                                <label class="required" for="id_cover">Cover:</label>

                                    <input type="file" name="cover" required="" id="id_cover">


                        </div>

                </div>


        </div>

        <div class="form-row field-file">


                <div>

                        <div class="flex-container">

                                <label class="required" for="id_file">File:</label>

                                    <input type="file" name="file" required="" id="id_file" class="file">


                        </div>

                </div>


        </div>


</fieldset>


<div class="container"><input type="submit" value="Add" class="default" name="_save"></div>

</form>

{% endblock %}

SVP/videos/templates/videos/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    <title>Video Platform</title>
</head>
<body>
    <div class="container">

        {% block 'body' %}
        {% endblock %}
    </div>
</body>
</html>

SVP/videos/templates/videos/change_video_page.html
{% extends 'videos/base.html' %}

{% block 'body' %}


<form enctype="multipart/form-data" method="post" id="video_form" novalidate="">
{% csrf_token %}



<fieldset class="module aligned ">

        <div class="form-row field-title">


                <div>

                        <div class="flex-container">

                                <label class="required" for="id_title">Title:</label>

                                    <input type="text" name="title" class="vTextField" maxlength="25" required="" id="id_title">


                        </div>

                </div>


        </div>

        <div class="form-row field-cover">


                <div>

                        <div class="flex-container">

                                <label class="required" for="id_cover">Cover:</label>

                                    <input type="file" name="cover" required="" id="id_cover">


                        </div>

                </div>


        </div>

        <div class="form-row field-file">


                <div>

                        <div class="flex-container">

                                <label class="required" for="id_file">File:</label>

                                    <input type="file" name="file" required="" id="id_file">


                        </div>

                </div>


        </div>


</fieldset>

<div class="container"><input type="submit" value="Change" class="default" name="_change"></div>

</form>

{% endblock %}

SVP/videos/templates/videos/channel.html
{% extends 'videos/base.html' %}


{% block 'body' %}
<div class="container">
    <h1>{{account}}</h1>
        <div class="container">
            {% for video in videos %}
                <div class="video_container">
                    <a href="/view/{{video.id}}" class="no-underline">
                    <img src="{{ video.cover.url }}" width="300" height="200" alt="{{video.title}}">
                    <h3>{{video.title}}</h3>
                    <h6>{{video.uploaded_at}}</h6>
                    </a>
                </div>
            {% endfor %}
        </div>

</div>

{% endblock %}

SVP/videos/templates/videos/delete_video_page.html
{% extends 'videos/base.html' %}


{% block 'body' %}
    <div class="main">
        <form method="post">
            {% csrf_token %}
            <h1>Do you want to delete video ?</h1>
            <input type="submit" value="Yes I'm sure, delete it">
        </form>
    </div>

{% endblock %}

SVP/videos/templates/videos/find_page.html
{% extends 'videos/base.html' %}


{% block 'body' %}
<div class="container">
        {% if video %}
        <div class="video_container">
            <a href="/view/{{video.id}}" class="no-underline">
            <img src="{{ video.cover.url }}" width="300" height="200" alt="{{video.title}}">
            <h3>{{video.title}}</h3>
            <h6>{{video.uploaded_at}}</h6>
            </a>
        </div>
        {% else %}
            <h2>Not found any video</h2>
        {% endif %}
</div>

{% endblock %}

SVP/videos/templates/videos/main.html
{% extends 'videos/base.html' %}


{% block 'body' %}
<div class="container"><a href="/create" class="blue-link">Create account</a>
        <a href="/login" class="blue-link">Log In</a></div>
    <p></p>
    <form method="post">
        {% csrf_token %}
        <div class="container">
            <input type="search" placeholder="video platform" name="data" class="search_inp">
            <input type="submit" value="search">
        </div>
    </form>
    {% for video in videos %}

        <div class="video_container">
            <a href="/view/{{video.id}}" class="no-underline">
            <img src="{{ video.cover.url }}" width="300" height="200" alt="{{video.title}}">
            <h3>{{video.title}}</h3>
            <h6>{{video.uploaded_at}}</h6>
            </a>
        </div>
    {% endfor %}


{% endblock %}

SVP/videos/templates/videos/view_page.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/video.css' %}">

    <title>Video Platform</title>
</head>
<body>
    <div class="vd">
            {% if error %}
                <h1>{{ error }}</h1>
            {% else %}
                <div>

                    <video width="640" height="360" controls>
                       <source src="{{video.file.url}}" type="video/mp4">
                       <source src="{{video.file.url}}" type="video/ogg">
                    </video>
                    <h3>{{video.title}}</h3>
                    <a class="channel-link" href="/channel/{{video.account.id}}"><h3>{{video.account}}</h3></a>
                    <h6>{{video.uploaded_at}}</h6>

                </div>
            {% endif %}
    </div>
</body>
</html>